[package]
name = "fwx"
version = "0.1.0"
edition = "2024"
description = "A firmware analysis TUI for reverse engineers"
license = "MIT"
repository = "https://github.com/NikOffSec/fwx_tool"
readme = "README.md"
keywords = ["firmware", "reverse-engineering", "binwalk", "tui", "security"]
categories = ["command-line-utilities", "development-tools::debugging"]
exclude = ["release/"]

[dependencies]
anyhow = "1.0.103"
binwalk = "3.1.0"
capstone = "0.14.0"
crossterm = "0.29.0"
object = "0.39.1"
ratatui = "0.30.2"
rust-strings = "0.6.5"

[[bin]]
name = "fwx"
path = "src/main.rs"
